version: 2.1

jobs:
  install-deps:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: yarn install --frozen-lockfile --non-interactive
      - run: yarn --cwd aio --frozen-lockfile --non-interactive
      - run: yarn --cwd packages/compiler-cli --frozen-lockfile --non-interactive
      - run: yarn --cwd packages/core/schematics --frozen-lockfile --non-interactive
      - run: yarn --cwd packages --frozen-lockfile --non-interactive
      - run: yarn --cwd packages/service-worker/cli --frozen-lockfile --non-interactive
      - run: yarn --cwd packages/zone.js --frozen-lockfile --non-interactive
      - run: yarn --cwd modules/benchmarks --frozen-lockfile --non-interactive
      - run: yarn --cwd modules --frozen-lockfile --non-interactive
      - save_cache:
          paths:
            - node_modules
            - website/node_modules
          key: dependencies
  lsif_aio:
    docker:
      - image: sourcegraph/lsif-node@sha256:943e620468baa9c1ad01a469e4ada02221105c6c4172542c8136965e482db791
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies
      - run: lsif-tsc -p ./aio/tsconfig.json
      - run: src lsif upload -no-progress -root=./aio
  lsif_packages_compiler_cli:
    docker:
      - image: sourcegraph/lsif-node@sha256:943e620468baa9c1ad01a469e4ada02221105c6c4172542c8136965e482db791
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies
      - run: lsif-tsc -p ./packages/compiler-cli/tsconfig.json
      - run: src lsif upload -no-progress -root=./packages/compiler-cli
  lsif_packages_core_schematics:
    docker:
      - image: sourcegraph/lsif-node@sha256:943e620468baa9c1ad01a469e4ada02221105c6c4172542c8136965e482db791
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies
      - run: lsif-tsc -p ./packages/core/schematics/tsconfig.json
      - run: src lsif upload -no-progress -root=./packages/core/schematics
  lsif_packages:
    docker:
      - image: sourcegraph/lsif-node@sha256:943e620468baa9c1ad01a469e4ada02221105c6c4172542c8136965e482db791
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies
      - run: lsif-tsc -p ./packages/tsconfig.json
      - run: src lsif upload -no-progress -root=./packages
  lsif_packages_service_worker_cli:
    docker:
      - image: sourcegraph/lsif-node@sha256:943e620468baa9c1ad01a469e4ada02221105c6c4172542c8136965e482db791
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies
      - run: lsif-tsc -p ./packages/service-worker/cli/tsconfig.json
      - run: src lsif upload -no-progress -root=./packages/service-worker/cli
  lsif_packages_zone_js:
    docker:
      - image: sourcegraph/lsif-node@sha256:943e620468baa9c1ad01a469e4ada02221105c6c4172542c8136965e482db791
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies
      - run: lsif-tsc -p ./packages/zone.js/tsconfig.json
      - run: src lsif upload -no-progress -root=./packages/zone.js
  lsif_modules_benchmarks:
    docker:
      - image: sourcegraph/lsif-node@sha256:943e620468baa9c1ad01a469e4ada02221105c6c4172542c8136965e482db791
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies
      - run: lsif-tsc -p ./modules/benchmarks/tsconfig.json
      - run: src lsif upload -no-progress -root=./modules/benchmarks
  lsif_modules:
    docker:
      - image: sourcegraph/lsif-node@sha256:943e620468baa9c1ad01a469e4ada02221105c6c4172542c8136965e482db791
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies
      - run: lsif-tsc -p ./modules/tsconfig.json
      - run: src lsif upload -no-progress -root=./modules

workflows:
  lsif-node:
    jobs:
      - install-deps
      - lsif_aio:
          requires:
            - install-deps
      - lsif_packages_compiler_cli:
          requires:
            - install-deps
      - lsif_packages_core_schematics:
          requires:
            - install-deps
      - lsif_packages:
          requires:
            - install-deps
      - lsif_packages_service_worker_cli:
          requires:
            - install-deps
      - lsif_packages_zone_js:
          requires:
            - install-deps
      - lsif_modules_benchmarks:
          requires:
            - install-deps
      - lsif_modules:
          requires:
            - install-deps
